### ISSUE TITLE
Code doesn't run on GPU

### ISSUE THREAD

**Issue by liuquande** [tensorflow/federated#832]
**Describe the bug**

I am building my own project with tensorflow federated learning API.
When running my code, the GPU is visible (as shown below), but the computation of federated learining was not done on GPU.

**System output to show that the gpu is indeed added**
```
2020-04-20 21:36:49.347491: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-04-20 21:36:49.347853: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-20 21:36:49.355351: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3499685000 Hz
2020-04-20 21:36:49.356094: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55957a6a65e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-20 21:36:49.356124: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-20 21:36:49.421125: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55957a6c9c90 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-04-20 21:36:49.421170: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX TITAN X, Compute Capability 5.2
2020-04-20 21:36:49.422796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX TITAN X computeCapability: 5.2
coreClock: 1.076GHz coreCount: 24 deviceMemorySize: 11.93GiB deviceMemoryBandwidth: 313.37GiB/s
2020-04-20 21:36:49.422898: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-04-20 21:36:49.422959: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-20 21:36:49.423015: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-04-20 21:36:49.423068: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-04-20 21:36:49.423182: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-04-20 21:36:49.423287: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-04-20 21:36:49.423351: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-20 21:36:49.427345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-04-20 21:36:49.427454: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-04-20 21:36:49.430516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-20 21:36:49.430573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-04-20 21:36:49.430624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-04-20 21:36:49.434605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11498 MB memory) -> physical GPU (device: 0, name:
 GeForce GTX TITAN X, pci bus id: 0000:01:00.0, compute capability: 5.2)
```

**Environment (please complete the following information):**
* Linux Ubuntu 16.04
* Python package versions

When running `pip freeze | grep tensorflow`, I got:
```
tensorflow==2.1.0
tensorflow-addons==0.8.3
tensorflow-estimator==2.1.0
tensorflow-federated==0.13.1
tensorflow-model-optimization==0.2.1
tensorflow-privacy==0.2.2
```
When running `pip3 freeze | grep tensorflow`, I got:
```
tensorflow==2.1.0
tensorflow-estimator==2.1.0
tensorflow-gpu==2.1.0
```
* Python version: Python3.7

* CUDA/cuDNN version:
CUDA Version 10.2.89

**Expected behavior**
Here is my code to perform federated training:
```
    federated_train_data = [dataset, dataset]
    trainer = tff.learning.build_federated_averaging_process(model_fn,\
            client_optimizer_fn=lambda: keras.optimizers.Adam(lr=args.lr, clipnorm=0.001),
            server_optimizer_fn=lambda: keras.optimizers.Adam(lr=args.lr, clipnorm=0.001))

    state = trainer.initialize()
    for i in range(1000):
        state, metrics = trainer.next(state, federated_train_data)
        print('round  {}, metrics={}'.format(str(i), metrics))
```
The training can be done successfully, but not on GPU. Training speed is very slow.

**Other information**
I install the environment following the instruction, by typing 'pip install --upgrade tensorflow_federated'.

An interesting thing is that when I use 'fit()' to perform model training shown above rather than using federated learning, the computation can be done on GPU.

Many thanks for your help!

**Comment by liuquande** [comment]
Can anyone help me?   Many thanks！

**Comment by nightldj** [comment]
@liuquande Thanks for the detailed description. tff.learning.federated_averaging currently uses features from TF that will default to CPUs and it is expected to be fixed in the next TF version. 

For now, to have a better utility of GPUs, my suggestion would be to look at the simple_fedavg (https://github.com/tensorflow/federated/tree/master/tensorflow_federated/python/research/simple_fedavg) implementation to see if you can use the federated averaging algorithms there. It should only require very small changes to your code. 

Also note that multi-GPU support is under development. We do not have a solution for now.

**Comment by liuquande** [comment]
Hi @nightldj, thanks for the suggestion.

As suggested, I try to run the simple_fedavg demo to see the GPU util rate. ((https://github.com/tensorflow/federated/tree/master/tensorflow_federated/python/research/simple_fedavg)))

When running the code (without any change) using bazel :
`
bazel run tensorflow_federated/python/research/simple_fedavg:emnist_fedavg_main
`

I got the following error:
```
iceDataset shapes: OrderedDict([(label, ()), (pixels, (28, 28))]), types: OrderedDict([(label, tf.int32), (pixels, tf.float32)])>, <TensorSliceDataset shapes: OrderedDict([(label, ()), (pixels, (28, 28))]), types
: OrderedDict([(label, tf.int32), (pixels, tf.float32)])>, <TensorSliceDataset shapes: OrderedDict([(label, ()), (pixels, (28, 28))]), types: OrderedDict([(label, tf.int32), (pixels, tf.float32)])>, <TensorSliceD
ataset shapes: OrderedDict([(label, ()), (pixels, (28, 28))]), types: OrderedDict([(label, tf.int32), (pixels, tf.float32)])>, <TensorSliceDataset shapes: OrderedDict([(label, ()), (pixels, (28, 28))]), types: Or
deredDict([(label, tf.int32), (pixels, tf.float32)])>] with type list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/qdliu/.cache/bazel/_bazel_qdliu/0f8dd53c2bb702a191b3aefae090b80a/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.run
files/org_tensorflow_federated/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.py", line 181, in <module>
    app.run(main)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/data/home/qdliu/.cache/bazel/_bazel_qdliu/0f8dd53c2bb702a191b3aefae090b80a/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.run
files/org_tensorflow_federated/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.py", line 146, in main
    train_data, test_data = get_emnist_dataset()
  File "/data/home/qdliu/.cache/bazel/_bazel_qdliu/0f8dd53c2bb702a191b3aefae090b80a/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.run
files/org_tensorflow_federated/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.py", line 79, in get_emnist_dataset
    emnist_test.create_tf_dataset_from_all_clients())
  File "/data/home/qdliu/.cache/bazel/_bazel_qdliu/0f8dd53c2bb702a191b3aefae090b80a/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.run
files/org_tensorflow_federated/tensorflow_federated/python/simulation/client_data.py", line 112, in create_tf_dataset_from_all_clients
    nested_dataset = tf.data.Dataset.from_tensor_slices(client_datasets)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 644, in from_tensor_slices
    return TensorSliceDataset(tensors)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2784, in __init__
    element = structure.normalize_element(element)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/tensorflow_core/python/data/util/structure.py", line 98, in normalize_element
    ops.convert_to_tensor(t, name="component_%d" % i))
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1314, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 317, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 258, in constant
    allow_broadcast=True)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 266, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (<TensorSliceDataset shapes: OrderedDict([(label, ()), (pixels, (28, 28))]), types: OrderedDict([(label, tf.int32), (pixels, tf.float32)])>) with an unsupported type (<class
 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>) to a Tensor.
```
To avoid this error, I try to build the validation data with the code from image classification tutorial like follows:
```
def preprocess(dataset):

  def batch_format_fn(element):
    """Flatten a batch `pixels` and return the features as an `OrderedDict`."""
    return collections.OrderedDict(
        x=tf.expand_dims(element['pixels'], -1), y=element['label'])

  return dataset.repeat(50).batch(20).map(batch_format_fn).prefetch(20)

def get_emnist_dataset():
  """Loads and preprocesses the EMNIST dataset.

  Returns:
    A `(emnist_train, emnist_test)` tuple where `emnist_train` is a
    `tff.simulation.ClientData` object representing the training data and
    `emnist_test` is a single `tf.data.Dataset` representing the test data of
    all clients.
  """
  emnist_train, emnist_test = tff.simulation.datasets.emnist.load_data(
      only_digits=True)

  def element_fn(element):
    return collections.OrderedDict(
        x=tf.expand_dims(element['pixels'], -1), y=element['label'])

  def preprocess_train_dataset(dataset):
    # Use buffer_size same as the maximum client dataset size,
    # 418 for Federated EMNIST
    return dataset.map(element_fn).shuffle(buffer_size=418).repeat(
        count=FLAGS.client_epochs_per_round).batch(
            FLAGS.batch_size, drop_remainder=False)

  def preprocess_test_dataset(dataset):
    return dataset.batch(FLAGS.test_batch_size, 
      drop_remainder=False).map(element_fn)

  emnist_test = preprocess(emnist_train.create_tf_dataset_for_client(
    emnist_train.client_ids[0]))

  emnist_train = emnist_train.preprocess(preprocess_train_dataset)

  return emnist_train, emnist_test
```

Then I get another error: 
```
Traceback (most recent call last):
  File "/data/home/qdliu/.cache/bazel/_bazel_qdliu/0f8dd53c2bb702a191b3aefae090b80a/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.py", line 191, in <module>
    app.run(main)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/data/home/qdliu/.cache/bazel/_bazel_qdliu/0f8dd53c2bb702a191b3aefae090b80a/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.py", line 167, in main
    server_state = iterative_process.initialize()
  File "/data/home/qdliu/.cache/bazel/_bazel_qdliu/0f8dd53c2bb702a191b3aefae090b80a/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/utils/function_utils.py", line 563, in __call__
    return context.invoke(self, arg)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/data/home/qdliu/.cache/bazel/_bazel_qdliu/0f8dd53c2bb702a191b3aefae090b80a/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.runfiles/six/__init__.py", line 693, in reraise
    raise value
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/data/home/qdliu/.cache/bazel/_bazel_qdliu/0f8dd53c2bb702a191b3aefae090b80a/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/simple_fedavg/emnist_fedavg_main.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/execution_context.py", line 203, in invoke
    _invoke(executor, comp, arg)))
  File "/home/qdliu/anaconda/envs/tff0.13/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
RuntimeError: generator raised StopIteration
```

Could you please give me some more advices?
Thank you very much for your time and help!

**Comment by pepper-jk** [comment]
> @liuquande Thanks for the detailed description. tff.learning.federated_averaging currently uses features from TF that will default to CPUs and it is expected to be fixed in the next TF version.

Could you provide a link to the issue in the TF repo?
I'd like to look for their fix and maybe compile TF myself in order to use it sooner rather than later?

**Comment by nightldj** [comment]
@pepper-jk I am not pretty sure how to map internal report to public issue, but TF code after Apr 16 should have fixed the problem. You can compile any TF version after Apr 16.  

@liuquande simple_fedavg runs OK on my side. My guess is that you are running the most recent version of simple_fedavg with the pip installed TFF. Could you try run an older version of simple_fedavg, like the following one that has the v0.13.1 tag on it? https://github.com/tensorflow/federated/commit/464c2758a03a70dfe36a7df1919840a79983a7aa#diff-37f984101ae57f942ed47cb6102d4190
Or compile the most recent TFF?

**Comment by pepper-jk** [comment]
So I build tensorflow master at 0493a020d48081b6f2afb53a1ac9d45b2861c03d and there is no significant improvement in performance.

It seems to use the GPU but only every few seconds and only at 70%.

**Comment by liuquande** [comment]
@pepper-jk 
Yes, I was monitoring the GPU usage all the time when running the demo code, but my usage is 0% (sometime could be 6% or 7%).
Did you run the demo code or your own code? I mean the program that can successfully use GPU for 70%.

**Comment by pepper-jk** [comment]
It's our own code.

Just wanted to make sure you did not miss the GPU usage, because I did at first with just manually using `nvidia-smi`.

**Comment by liuquande** [comment]
@pepper-jk 
Thanks for your reminding.
What's your GPU usage before installing tensorflow master.
Could you please try the image classification demo here "https://paste.ubuntu.com/p/sPtqngFPWP/",
and have a look at the GPU usage.

**Comment by pepper-jk** [comment]
Sadly I can not. Our GPU memory is full at the time with since our experiments are currently running anyway. We need the results and in case it turns out the GPU can't be utilized completely we need to keep it running like this.

However we only changed the [tutorial](https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification) code very slightly, for example to use tensorflow-privacy as well.
So I doubt we have a much different setup then you do.
What we probably do differently is that we use the full dataset.

For more information on our dataset setup look in this [issue](https://github.com/tensorflow/federated/issues/833).

> When running my own code, sometimes I can also observe a higher usage such as 30%, but in most time, the usage is 0%.

Yes, like I said we at most get 35% from one instance (we have two running, please see above).

**Comment by liuquande** [comment]
@pepper-jk 
Many thanks for your informaiton.
Did you think installing the up-to-date tensorflow master improve your GPU usage?

**Comment by pepper-jk** [comment]
From what I can see no.
However maybe @nightldj will have some more information.

I'm currently compiling the master of today, seeing if this will change anything, but I doubt it.

Any luck with the "simple avg" function, that was named as an alternative?

**Comment by liuquande** [comment]
Sorry what do you mean by:
>Any luck with the "simple avg" function, that was named as an alternative?


I can now successfully run the 'simple_ave' demo, but also the GPU usage is low.
Sometime it could be 20% but in most time it is 0%, see below.
![image](https://user-images.githubusercontent.com/29408526/80093280-c2eb2380-8596-11ea-9de4-1e0dc600f861.png)

**Comment by pepper-jk** [comment]
You basically answered my question.
I was wondering if the performance improved.

**Comment by nightldj** [comment]
@pepper-jk It is a bit tricky to use the local TF. Sorry if I confused you at the beginning. You probably have to build TFF following the instructions here https://www.tensorflow.org/federated/install#build_the_tensorflow_federated_pip_package. Also, you have to make sure TF is installed in your local python environment, or build a pip package to be installed in the TFF environment. 

@liuquande simple_fedavg has a relatively small workload which may not saturate GPU utility. I am not sure how to correctly measure here, but there are a few  things you can do to check if GPU is used: (1) compare GPU and CPU to verify speedup (2) compare with pure TF on GPU (3) You can make the workload much larger by using a deeper model in simple_fedavg.

**Comment by pepper-jk** [comment]
> @pepper-jk It is a bit tricky to use the local TF. Sorry if I confused you at the beginning. You probably have to build TFF following the instructions here https://www.tensorflow.org/federated/install#build_the_tensorflow_federated_pip_package. Also, you have to make sure TF is installed in your local python environment, or build a pip package to be installed in the TFF environment.

I have build TF and installed it as a pip package in my venv. I did not have any problems with TFF detecting the package, since the TF package I build and installed is labeled as version 2.1.

What I was asking is, if the fix you referred to was perhaps made in TFF - not TF like you said. And if this is the reason why I did not see any improvements?

If so I will gladly also build TFF from scratch.

**Comment by nightldj** [comment]
@pepper-jk Thanks for verifying the TF installation. The fix is from TF, not TFF. Do you mean the TF version in TFF after your local TF installation is 2.1 can confirm that the correct TF is used? I am not the expert on installation stuff. If it is not too much trouble, would you mind building TFF following https://www.tensorflow.org/federated/install#build_the_tensorflow_federated_pip_package? You can stop after step #5 if you only want to test and donot want to build a pip package. 

Would you also share some evidence on 'did not see any improvements'? Sorry if you have mentioned before. 

And thanks for exploring the usage of TFF.

**Comment by pepper-jk** [comment]
> Would you also share some evidence on 'did not see any improvements'? Sorry if you have mentioned before.

Here you go from my earlier post:

> It seems to use the GPU but only every few seconds and only at 70%.
> 
> Please note that the experiment from 2 days ago is also still running and today I also noticed that it utilizes the GPU from time to time. So the actual GPU usage per instance is more around 35%

> If it is not too much trouble, would you mind building TFF following https://www.tensorflow.org/federated/install#build_the_tensorflow_federated_pip_package?

I can do that. But what exactly is the goal with this? Just running the tests with my locally build TF package?

**Comment by nightldj** [comment]
@pepper-jk I guess I just want to double check that the fixed TF is used in TFF. In my humble opinion, GPU utility depends on a lot of factors. And I would look for more evidence: (1) compare GPU and CPU to verify speedup (2) compare with pure TF on GPU (3) Sanity check on model training workload and data pipeline.

**Comment by aqibsaeed** [comment]
@nightldj does it mean that if we install TFF via pip, it is possible to train model on GPU? is training on the GPU is default now?

**Comment by nightldj** [comment]
@aqibsaeed The default of TFF is similar to TF: if GPU is provided, TFF/TF will try to use it. But TFF on GPUs is under development and have not been broadly tested. We have been working on the performance and made some progresses, but we are not at a point to confidently advertise GPU usage for now.

**Comment by pepper-jk** [comment]
> @aqibsaeed The default of TFF is similar to TF: if GPU is provided, TFF/TF will try to use it. But TFF on GPUs is under development and have not been broadly tested. We have been working on the performance and made some progresses, but we are not at a point to confidently advertise GPU usage for now.

So any update? When can we expect these improvements?
Is there something we could contribute to speed up the process? Maybe you want to open some more detailed issues on this topic that specifies required implementations to solve this?

**Comment by pepper-jk** [comment]
> @pepper-jk I guess I just want to double check that the fixed TF is used in TFF. In my humble opinion, GPU utility depends on a lot of factors. And I would look for more evidence: (1) compare GPU and CPU to verify speedup (2) compare with pure TF on GPU (3) Sanity check on model training workload and data pipeline.

@nightldj You might be right about the tests though:

```
Executed 115 out of 136 tests: 35 tests pass and 101 fail locally.
```

[full log](https://pastebin.com/SNfpBhtH)

I switched to tf-nightly for more up to date tf instead of building it myself. And I pulled the most current tff to run the tests.
I had similar results with my personal tf build and "older" versions of tff about a week ago.

So any advice to fix this?
Is the GPU usage related to these failed tests?

**Comment by nightldj** [comment]
@pepper-jk We do know some GPU incompatible issues, and I have workaround committed in https://github.com/tensorflow/federated/commit/aec461ba9fee36a05704748041af2f94cc5e31c0. All TFF tests should run without error on GPU after the fix. 

All my GPU tests are on P100/V100 with CUDA. At the head of TFF and TF, I have found one GPU works fine except for the known problem I tagged in test.  Multi-GPU is under development and we have to work with TF on that.

**Comment by pepper-jk** [comment]
> @pepper-jk We do know some GPU incompatible issues

Please open some new issues here on github with more detailed information, so we might contribute to the solution. Or point to existing ones, if I missed them.

> and I have workaround committed in [aec461b](https://github.com/tensorflow/federated/commit/aec461ba9fee36a05704748041af2f94cc5e31c0).

How is this a **workaround** for the issues with the GPU? You just skip the tests on GPU. Maybe you could call this a workaround for your CI, but not for the issue itself.

> All TFF tests should run without error on GPU after the fix.

Okay, thanks for the information. I will try to get all the tests running on my system before further testing. Any idea what it could be? Could you take a look at the log I posted?

> All my GPU tests are on P100/V100 with CUDA. At the head of TFF and TF, I have found one GPU works fine except for the known problem I tagged in test. Multi-GPU is under development and we have to work with TF on that.

We are not asking for multi GPU support. From what I understand we are all using single GPU setups. We are simple stating that the GPU is barely being utilized.

**Comment by pepper-jk** [comment]
I've got more information on the failing tests.

<details><summary>I looked into some of the logs in .cache and found this error repeatedly:</summary>
<p>

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tensorflow_federated/python/core/impl/executors:sizing_executor_test
-----------------------------------------------------------------------------
2020-05-12 09:19:11.112671: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so
.10.1
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/721/execroot/org_tensorflow_fed
erated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflo
w_federated/python/core/impl/executors/sizing_executor_test.py", line 21, in <module>
    import tensorflow as tf
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 53, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

</p>
</details>

I **fixed** it with: `pip install --upgrade pip setuptools`

Before:
```Executed 116 out of 136 tests: 21 tests pass and 115 fail locally.```
After:
```Executed 115 out of 136 tests: 48 tests pass and 88 fail locally.```

The other tests seem to be failing since the GPU is out of memory.
Once the server has less load, I'll run the tests again to confirm this.



<details><summary>example error log for oom ([complete log](https://pastebin.com/j3hv9dZ9)):</summary>
<p>

```
[  FAILED  ] SizingExecutorTest.test_executor_stacks_big_caching_stack
======================================================================
ERROR: test_executor_stacks_big_caching_stack (__main__.SizingExecutorTest)
test_executor_stacks_big_caching_stack (__main__.SizingExecutorTest)
test_executor_stacks_big_caching_stack([<class 'tensorflow_federated.python.core.impl.executors.sizing_executor.SizingExecutor'>, <class 'tensorflow_federated.python.core.impl.executors.caching_executor.CachingExecutor'>, <class 'tensorflow_federated.python.core.impl.executors.reference_resolving_executor.ReferenceResolvingExecutor'>, <class 'tensorflow_federated.python.core.impl.executors.caching_executor.CachingExecutor'>, <class 'tensorflow_federated.python.core.impl.executors.caching_executor.CachingExecutor'>, <class 'tensorflow_federated.python.core.impl.executors.reference_resolving_executor.ReferenceResolvingExecutor'>, <class 'tensorflow_federated.python.core.impl.executors.caching_executor.CachingExecutor'>])
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/absl/testing/parameterized.py", line 265, in bound_param_test
    test_method(self, *testcase_params)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/sizing_executor_test.py", line 238, in test_executor_stacks
    asyncio.get_event_loop().run_until_complete(_make())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/sizing_executor_test.py", line 235, in _make
    v1 = await ex.create_value(outer_type_val, outer_type)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/sizing_executor.py", line 107, in create_value
    target_val = await self._target.create_value(value, type_spec)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/caching_executor.py", line 251, in create_value
    raise e
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/caching_executor.py", line 243, in create_value
    await cached_value.target_future
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/common_libs/tracing.py", line 201, in async_trace
    result = await fn(*fn_args, **fn_kwargs)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/reference_resolving_executor.py", line 283, in create_value
    *[self.create_value(val, t) for (_, val), t in zip(v_el, type_spec)])
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/common_libs/tracing.py", line 201, in async_trace
    result = await fn(*fn_args, **fn_kwargs)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/reference_resolving_executor.py", line 283, in create_value
    *[self.create_value(val, t) for (_, val), t in zip(v_el, type_spec)])
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/common_libs/tracing.py", line 201, in async_trace
    result = await fn(*fn_args, **fn_kwargs)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/reference_resolving_executor.py", line 290, in create_value
    value, type_spec))
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/caching_executor.py", line 251, in create_value
    raise e
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/caching_executor.py", line 243, in create_value
    await cached_value.target_future
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/caching_executor.py", line 251, in create_value
    raise e
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/caching_executor.py", line 243, in create_value
    await cached_value.target_future
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/common_libs/tracing.py", line 201, in async_trace
    result = await fn(*fn_args, **fn_kwargs)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/reference_resolving_executor.py", line 290, in create_value
    value, type_spec))
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/caching_executor.py", line 251, in create_value
    raise e
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/caching_executor.py", line 243, in create_value
    await cached_value.target_future
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/common_libs/tracing.py", line 201, in async_trace
    result = await fn(*fn_args, **fn_kwargs)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/eager_tf_executor.py", line 406, in create_value
    return EagerValue(value, self._tf_function_cache, type_spec, self._device)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/eager_tf_executor.py", line 309, in __init__
    type_spec, device)
  File "/home/user/.cache/bazel/_bazel_user/a5689464ec704691e1f2141aa12ce976/sandbox/linux-sandbox/929/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/core/impl/executors/sizing_executor_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/core/impl/executors/eager_tf_executor.py", line 262, in to_representation_for_type
    value = tf.convert_to_tensor(value, dtype=type_spec.dtype)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1432, in convert_to_tensor_v2
    as_ref=False)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1490, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 328, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 263, in constant
    allow_broadcast=True)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 271, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    ctx.ensure_initialized()
  File "/home/user/code/venv_clean/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 533, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory

----------------------------------------------------------------------
Ran 1 test in 20.471s

FAILED (errors=1)
```

</p>
</details>

**Comment by pepper-jk** [comment]
> @pepper-jk We do know some GPU incompatible issues, and I have workaround committed in [aec461b](https://github.com/tensorflow/federated/commit/aec461ba9fee36a05704748041af2f94cc5e31c0). All TFF tests should run without error on GPU after the fix.

<details><summary>The computation test you are referring to is passing on our server.</summary>
<p>

```
$ bazel test //tensorflow_federated/python/core/api:computations_test
INFO: Analyzed target //tensorflow_federated/python/core/api:computations_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //tensorflow_federated/python/core/api:computations_test up-to-date:
  bazel-bin/tensorflow_federated/python/core/api/computations_test
INFO: Elapsed time: 38.514s, Critical Path: 38.25s
INFO: 10 processes: 10 linux-sandbox.
INFO: Build completed successfully, 11 total actions
//tensorflow_federated/python/core/api:computations_test                 PASSED in 38.2s
  Stats over 10 runs: max = 38.2s, min = 25.4s, avg = 30.2s, dev = 5.1s

INFO: Build completed successfully, 11 total actions
```

</p>
</details>

I was able to run the test on its own, so I do not run into the issue of the GPU running out of memory due to the other tests that are run in parallel.

So now that I can confirm the `tf-nightly` install is sufficient to run the current tf-federated master, I assume the next step would be to revert the commit you mentioned (aec461ba9fee36a05704748041af2f94cc5e31c0) and run the tests again.

Then from the test results I'll look into the code that needs fixing, but clear issue descriptions on the implementation needed would still be much appreciated. Even general ideas or resources.

**Comment by pepper-jk** [comment]
> @pepper-jk We do know some GPU incompatible issues, and I have workaround committed in [aec461b](https://github.com/tensorflow/federated/commit/aec461ba9fee36a05704748041af2f94cc5e31c0). All TFF tests should run without error on GPU after the fix.
> 
> All my GPU tests are on P100/V100 with CUDA. At the head of TFF and TF, I have found one GPU works fine except for the known problem I tagged in test. Multi-GPU is under development and we have to work with TF on that.

In your TODO you state:
```
# TODO(b/137602785): bring GPU test back after the fix for `wrap_function`
```

Do you refer to [this issue](https://github.com/tensorflow/tensorflow/issues/33585) regarding the `wrap_function`?

**Comment by nightldj** [comment]
Thanks for your test and continuous interests. Sorry you meet the parallel test issue on GPU. We fixed that internally, but not sure how to configure that without Google infra. 

 This commit 15fb10008921447690d1ea5a42829b9f9a7e832b might have fixed some of the GPU tests, but probably not all of them. If you could help identify which ones are fixed, we would appreciate it. 

The TODO refers to an internal issue. The closest one might be https://github.com/tensorflow/tensorflow/issues/34519
https://github.com/tensorflow/tensorflow/issues/34112 on the TF side.

**Comment by pepper-jk** [comment]
Any Updates?

**Comment by nightldj** [comment]
We have been using single GPU for a while. We will be surprised to know single GPU does not work with the recent release of TF and TFF. The performance might not be fully optimized and we have a few pending changes to improve, but single GPU should work as expected, i.e., much faster than CPU, and on par with pure TF.

**Comment by mirkohin1991** [comment]
I am still facing this issue. I am currently training a classifier on my own large dataset.

In a central setup, my keras model is trained successfully consuming the GPU.

When using TFF, the GPU is not used at all, so the training is not feasible.
![image](https://user-images.githubusercontent.com/6350053/93001709-65e60f00-f531-11ea-9b2e-1a7cdc5b1552.png)

**Comment by mirkohin1991** [comment]
I also tested it with colab and the image classification tutorial.
According to the wandb analyzer, the GPU is not used.
![image](https://user-images.githubusercontent.com/6350053/94151112-4f697d00-fe7a-11ea-8200-26a146d1cd00.png)

**Comment by nightldj** [comment]
@mirkohin1991 sorry just saw this thread. Please take a look at our colab tutorial for GPU usage https://www.tensorflow.org/federated/tutorials/simulations_with_accelerators. I will close this issue, but feel free to reopen if it is not resolved.
